### ISSUE TITLE
Overeager matching

### ISSUE THREAD

**Issue by Aerijo** [tree-sitter/tree-sitter-jsdoc#1]
The following is detected as an error and the recovery marks it as a variable
```
/**
 * it will search for a \begin{document} command
 */
```
Ideally it would play it safer and ignore any error like matches.

**Comment by MunifTanjim** [comment]
Single line comment are detected as error too.

```ts
// some comment
```

**Comment by amaanq** [comment]
variable isn't the right term, it parses document and command as identifiers, so on that end it seems fine, but I'll leave this up as it shouldn't error out to begin w/
