### ISSUE TITLE
Problem with automatic indentation of newlines

### ISSUE THREAD

**Issue by McAllaster** [tree-sitter/tree-sitter-jsdoc#3]
When the `jsdoc` module is enabled, treesitter's indentation is enabled, and given the following comment:

```javascript
/**
 * text
 */
 ```

Inserting a newline after "` * text`" produces the following:

```javascript
/**
 * text
*
 */
```

However, my expected result is:

```javascript
/**
 * text
 *
 */
```

Furthermore, if I don't have the `jsdoc` module enabled, the expected result is achieved.

I see that the `jsdoc` module doesn't have indentation as a feature, but would having the `jsdoc` module enabled then _disable_ the indentation granted by default?

Edit:

The above scenarios were tested with the `javascript` module installed/enabled at the same time, as it seems that `jsdoc` does not function without it.

<details>

<summary>treesitter healthcheck</summary>

```
health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v14.17.6 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - jsdoc          ✓ . . . . 
  - javascript     ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

```
</details>

**Comment by chearon** [comment]
Are you sure this isn't nvim-treesitter/nvim-treesitter#1167? I experience the problem even without the jsdoc grammar.

**Comment by McAllaster** [comment]
> Are you sure this isn't [nvim-treesitter/nvim-treesitter#1167](https://github.com/nvim-treesitter/nvim-treesitter/issues/1167)? I experience the problem even without the jsdoc grammar.

They _could_ be related. However, I only encounter this issue when `jsdoc` module is installed.

It's also worth noting that I seem to require the `javascript` module to be installed for `jsdoc` to work, and to encounter this issue. That is not something that I had noted above.

**Comment by maxbrunsfeld** [comment]
Can you open this issue on nvim tree sitter? This repo just contains a parser, not indent configuration.
