### ISSUE TITLE
Syntax color for JSDoc variable names

### ISSUE THREAD

**Issue by jimmywarting** [tree-sitter/tree-sitter-jsdoc#5]
VScode dose a wonderful job at highlighting JSDoc variable names so they are easier to read

here is an example of how VSCode syntax color looks like:

![image](https://github.com/github-linguist/linguist/assets/1148376/5fae53fe-3355-47bf-9b32-3a1aca8ed06f)

```js
/**
 * And this is how github markdown pressents it
 * 
 * @param {number} x This is a comment
 * @param {number} [y] this is another optional comment
 */
function add (x, y) {

}
```
All the comments being gray is fine, but i would wish for the variable name to be colored

ppl don't always include a `-` to separate out the variable name from the actual comment
like this:
```
 * @param {number} x - This is a comment
```
so it looks a bit weird as if the variable name is sometimes part of the actual comment in some cases

_Originally posted by @jimmywarting in https://github.com/github-linguist/linguist/issues/6426

**Comment by amaanq** [comment]
Querying allows you to distinguish x/y as you please, not sure what [y] is

**Comment by jimmywarting** [comment]
`[y]` is an [optional param](https://jsdoc.app/tags-param.html#optional-parameters-and-default-values).

**Comment by jimmywarting** [comment]
Don't know why this was closed, still wishes to have the variable name in jsdoc to be tokenized and colored.

currently it tokenize it as `<span>} x This is a comment</span>`
when i want it to be something like `<span class="var-name">x</span><span> This is a comment</span>`

desirable outcome: 
<img width="405" alt="image" src="https://github.com/tree-sitter/tree-sitter-jsdoc/assets/1148376/a9766b36-d73a-4ae9-8cf9-bdda95a5cac4">

current looks like
<img width="408" alt="image" src="https://github.com/tree-sitter/tree-sitter-jsdoc/assets/1148376/c2c8117b-9cc2-4c22-923c-93bb3d655ecc">

**Comment by amaanq** [comment]
I think there is a fundamental misunderstanding of what tree-sitter does vs. how GH uses it, they use their own queries to match stuff, that's not under our umbrella.

That being said, I've fixed optional parameter parsing, thanks.
