### ISSUE TITLE
@prop's argument is not being highlighted

### ISSUE THREAD

**Issue by thi-marques** [tree-sitter/tree-sitter-jsdoc#9]
[JSDoc](https://jsdoc.app/tags-property) says the tag `@prop` is synonym of the `@property` one.

But I noticed the `@prop`'s argument is not receiving the `@type.jsdoc` highlight group.

![image](https://github.com/tree-sitter/tree-sitter-jsdoc/assets/12144525/4c65bf40-f419-4382-9cc5-a899ca9a386e)

**Comment by amaanq** [comment]
Fixed now on master, please let me know of any others failing to parse.
